name: Publish to PyPI
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      publish:
        description: "Publish to pypi.org? (will not work from forks!)"
        required: false
        default: 'false'

permissions:
  contents: read

jobs:
  test:
    name: Test Release
    runs-on: ubuntu-latest
    steps:
      - name: Publish to pypi
        uses: coveooss/pypi-publish-with-poetry@84aa0405b3e10921dcab065f86b583a402dd58c8 # v1
        with:
          project-name: secrules-parsing
          pypi-token: ${{ secrets.PYPI_TOKEN }}
          pre-release: ${{ github.ref != 'refs/heads/master' }}
          dry-run: ${{ github.ref != 'refs/heads/master' && github.event.inputs.publish != 'true' }}
