name: Publish to PyPI
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      publish:
        description: "Publish to pypi.org? (will not work from forks!)"
        required: false
        default: 'false'

jobs:
  test:
    name: Test Release
    runs-on: ubuntu-latest
    steps:
      - name: Publish to pypi
        uses: coveooss/pypi-publish-with-poetry@1bd2d5f508b5a9973b7ab92a0f1ce97b8584bda0
        with:
          project-name: secrules-parsing
          pypi-token: ${{ secrets.PYPI_TOKEN }}
          pre-release: ${{ github.ref != 'refs/heads/master' }}
          dry-run: ${{ github.ref != 'refs/heads/master' && github.event.inputs.publish != 'true' }}
